### ISSUE TITLE
Electron support

### ISSUE THREAD

**Issue by kidwon24** [JoseExposito/v8-compiler#1]
I am keeping an eye on your project for a while, do you have any progress with the Electron support?

**Comment by JoseExposito** [comment]
This project started as an alternative to EncloseJS, but it was discontinued when pkg was released. I recommend you to use pkg, it is a fantastic tool.

**Comment by kidwon24** [comment]
Thank you.
Jose as a native programmer could you give me your estimation of how much `pkg` binaries  are 
vulnerable to reverse engineering?
Also could they be used with Electron?

**Comment by JoseExposito** [comment]
As vulnerable as compiled code. You can always read the “assembler” generated code.

About Electron support, I’m not sure about the status, you can ask to the pkg developer for support and future plans.
